#日志级别 debug、info、warn、error
LogLevel = "info"
# worker服务的监听地址
WorkerListenAddress = "127.0.0.1:6061"
# 网关服务唯一编号，如果配置不对，网关会返回注册错误
ServerId = 0
# 输出客户端界面的http服务的监听地址
ClientListenAddress = "0.0.0.0:80"
# url路由
HandlePattern = "/netsvr"
# 客户端心跳间隔，单位秒
HeartbeatInterval = 10
# customer服务的websocket连接地址
CustomerWsAddress = "wss://www.fool127.com:443/netsvr"
# 让worker为我开启n条协程来处理我的请求
ProcessCmdGoroutineNum = 3
# 业务进程注册到网关的工作id
WorkerId = 1
# 加密的key
SecretKey = "123456"
# 前端3d球的渲染数限制
Limit3D = 100
# 页面标题
PageTitle = "幸运大抽奖"
PageWelcome = "欢迎登录抽奖系统"